Add kafka connect
Tim01Bro/Mentee pull request #1
Opened 2023-09-20 17:33 UTC by Tim01Bro

2023-09-21 17:16 UTC, skalashynski commented
add `readme.md` file with description how to run a project

2023-09-21 17:16 UTC, skalashynski requested changes

2023-09-21 17:16 UTC, skalashynski commented on docker-compose.yml
> +      retries: 10
I do like healthchecks for postgres, can use the same for all services?

2023-09-21 17:16 UTC, skalashynski commented on docker-compose.yml
> +    depends_on: [zookeeper, kafka]
kafka depends on Zookeper so you can set only `kafka` here.

2023-09-22 06:45 UTC, NevarDima commented on initDB.sql
> +    id serial primary key,
I understand that there is no clear technical specification, but think about what constraints you can add to these fields, now you can add a completely empty record to your table

2023-09-22 06:48 UTC, NevarDima commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=1234
How about putting sensitive data (for example a password) into environment variables?

2023-10-07 14:58 UTC, merged